### ISSUE TITLE
Setting this.periodic.cur_period does not appear to work

### ISSUE THREAD

**Issue by lyonlim** [tra/periodic#2]
Hi,

I'm trying to assign a value to this while periodic is doing its loop, but it doesn't seem to have any effect.

I run periodic upon $(document).ready(function () {}); and I notice the first and 2nd iteration is almost immediately after. I'm trying to space the 2nd iteration further from the first.

**Comment by tra** [comment]
Try setting a variable to periodic then using that.   For example

```
var my_periodic = $.periodic(...);
my_periodic.cur_period = 42;
```
