### ISSUE TITLE
cancel wont work for me.

### ISSUE THREAD

**Issue by yo-l1982** [tra/periodic#3]
Great work on the plugin.
I cant get the cancel function to do what it is supposed to do i think.

Im not a pro but i hacked the cancel function to get it to work.

```
function cancel() {
    settings.tid = undefined;
}
```

I also needed to change the run function:
    function run() {
    // clear/stop existing timer (multiple calls to run() won't result in multiple timers)
    cancel();
    // let it rip!
    settings.tid = setTimeout(function() {
      // set the context (this) for the callback to the settings object
      callback.call(settings);

```
  if (settings.tid != undefined){
  // compute the next value for cur_period
  increment();
  // queue up the next run
  run();
  }
}, settings.cur_period);
}
```

got 2 periods running and this only affects the one i cancel.
If u got a better fix or an explanation why it not works for me ill be happy to hear.
yol

Edit: sry missed the earlier issue posted.

**Comment by jorgemanrubia** [comment]
Hi,

I had the same problem and, inspired by your comment, implemented a fix in the next branch.

http://github.com/jorgemanrubia/periodic/commit/ad6540470d2427f47b77d8a2018ac0e549b260f7

Thank you for sharing it. I thought it was me who was using the plugin incorrectly.

**Comment by yo-l1982** [comment]
Np.

Maybee I misinterpret the spec or something but I cant get it to work with clearTimeout.
But this way is fine, it works.

**Comment by tra** [comment]
Patch applied, thanks to Jorge!
